# Generated by Django 3.1 on 2020-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201022_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
