# Generated by Django 3.1 on 2020-11-02 04:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201025_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_content',
            field=ckeditor.fields.RichTextField(default='', max_length=1000),
        ),
    ]
