# Generated by Django 3.1 on 2020-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='event_image1',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(default='/static/img/logo.png', upload_to='img/eventimages'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image3',
            field=models.ImageField(default='/static/img/logo.png', upload_to='img/eventimages'),
        ),
    ]
