# Generated by Django 3.1 on 2020-11-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20201110_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image1',
            field=models.ImageField(default='img/logo.png', upload_to='img/eventimages'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(default='img/logo.png', upload_to='img/eventimages'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image3',
            field=models.ImageField(default='img/logo.png', upload_to='img/eventimages'),
        ),
    ]
