# Generated by Django 3.1 on 2020-11-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201113_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
    ]
