# Generated by Django 3.1 on 2020-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_content',
        ),
    ]
