# Generated by Django 3.1 on 2020-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=50)),
                ('blog_content', models.CharField(default='', max_length=5000)),
                ('blog_writer', models.CharField(default='scienceforum', max_length=50)),
                ('thumbnail', models.ImageField(default='/static/img/logo.png', upload_to='img/blogimg')),
            ],
        ),
    ]
