# Generated by Django 3.1 on 2020-10-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201024_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blod_date',
            new_name='blog_date',
        ),
    ]
