# Generated by Django 3.1 on 2020-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201026_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='usermail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
