# Generated by Django 3.1 on 2020-11-02 04:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201026_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='usermail',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
