# Generated by Django 3.1 on 2020-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20201102_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
