# Generated by Django 3.1.2 on 2020-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_title', models.CharField(default='', max_length=50)),
                ('Profile_content', models.CharField(default='', max_length=5000)),
                ('Profile_email', models.CharField(default='scienceforum', max_length=50)),
                ('Profie_thumbnail', models.ImageField(default='/static/img/logo.png', upload_to='img/blogimg')),
            ],
        ),
    ]
