# Generated by Django 3.1.2 on 2020-10-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='Profie_thumbnail',
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='Profile_Post',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='Profile_thumbnail',
            field=models.ImageField(default='media\\img\x08logimg\\science-1182713_1920.jpg', upload_to='media\\img\\profiles'),
        ),
    ]
