# Generated by Django 3.1 on 2020-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201025_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='Profile_thumbnail',
            field=models.ImageField(default='img/blogimg/science-1182713_1920.jpg', upload_to='img/profiles'),
        ),
    ]
