# Generated by Django 3.1.2 on 2020-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201025_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientistGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scientist_title', models.CharField(default='', max_length=50)),
                ('Scientist_content', models.CharField(default='', max_length=5000)),
                ('Profile_thumbnail', models.ImageField(default='img/blogimg/science-1182713_1920.jpg', upload_to='img/Scientist')),
            ],
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='Profile_thumbnail',
            field=models.ImageField(default='img/blogimg/science-1182713_1920.jpg', upload_to='img/profiles'),
        ),
    ]
