# Generated by Django 3.1.2 on 2020-10-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201027_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientistgallery',
            old_name='Profile_thumbnail',
            new_name='Scientist_thumbnail',
        ),
    ]
