# Generated by Django 3.1 on 2020-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201027_1051'),
        ('home', '0003_auto_20201025_1409'),
    ]

    operations = [
    ]
