# Generated by Django 3.1 on 2020-11-02 04:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20201027_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientistgallery',
            name='Scientist_content',
            field=ckeditor.fields.RichTextField(default='', max_length=5000),
        ),
    ]
