# Generated by Django 3.1 on 2020-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201102_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='admodal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('Image', models.ImageField(default='', upload_to='img/ads')),
                ('link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
