# Generated by Django 3.1.3 on 2020-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='priority',
            field=models.CharField(default='', max_length=5),
        ),
    ]
